### ISSUE TITLE
Ajustar formato do arquivo _LEIA.ME para _LEIAME.MD

### ISSUE THREAD

**Issue by jonatasemidio** [metaimagem/palavra-contada#2]
Usando a extensão MD podemos usar o MarkDown.

As descrições precisam ficar amigáveis para atrair contribuidores.

Se não souber como fazer só avisar ... mas na pior das hipóteses é só criar outro arquivo com o nome *.MD e add o texto nele, removendo o anterior em seguida.

**Comment by metaimagem** [comment]
done
